grails-app/domain/accounting/Accounts.groovy
package accounting

class Accounts {
    int id
    String name
    String number
    Double openingBalance
    String bankName
    String bankPhone
    String bankAddress
    Boolean isActive
    Date createdAt
    Date updatedAt
    Date deletedAt
    static constraints = {
        name(blank: false, maxSize: 50)
        number(blank: false,maxSize: 20)
        openingBalance()
        bankName(inList: ['Bank Asia','Brack Bank','City Bank','DBBL'])
        bankAddress()
        bankPhone()
        isActive()
    }
}

grails-app/controllers/accounting/AccountsController.groovy
package accounting



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AccountsController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Accounts.list(params), model:[accountsInstanceCount: Accounts.count()]
    }

    def show(Accounts accountsInstance) {
        respond accountsInstance
    }

    def detail(Accounts accountInstance){
        respond accountInstance
    }

    def create() {
        respond new Accounts(params)
    }

    @Transactional
    def save(Accounts accountsInstance) {
        if (accountsInstance == null) {
            notFound()
            return
        }

        if (accountsInstance.hasErrors()) {
            respond accountsInstance.errors, view:'create'
            return
        }

        accountsInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'accounts.label', default: 'Accounts'), accountsInstance.id])
                redirect accountsInstance
            }
            '*' { respond accountsInstance, [status: CREATED] }
        }
    }

    def edit(Accounts accountsInstance) {
        respond accountsInstance
    }

    @Transactional
    def update(Accounts accountsInstance) {
        if (accountsInstance == null) {
            notFound()
            return
        }

        if (accountsInstance.hasErrors()) {
            respond accountsInstance.errors, view:'edit'
            return
        }

        accountsInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Accounts.label', default: 'Accounts'), accountsInstance.id])
                redirect accountsInstance
            }
            '*'{ respond accountsInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Accounts accountsInstance) {

        if (accountsInstance == null) {
            notFound()
            return
        }

        accountsInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Accounts.label', default: 'Accounts'), accountsInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'accounts.label', default: 'Accounts'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/accounts/_form.gsp
<%@ page import="accounting.Accounts" %>



<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="accounts.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" maxlength="50" required="" value="${accountsInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'number', 'error')} required">
	<label for="number">
		<g:message code="accounts.number.label" default="Number" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="number" maxlength="20" required="" value="${accountsInstance?.number}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'openingBalance', 'error')} required">
	<label for="openingBalance">
		<g:message code="accounts.openingBalance.label" default="Opening Balance" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="openingBalance" value="${fieldValue(bean: accountsInstance, field: 'openingBalance')}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'bankName', 'error')} required">
	<label for="bankName">
		<g:message code="accounts.bankName.label" default="Bank Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="bankName" from="${accountsInstance.constraints.bankName.inList}" required="" value="${accountsInstance?.bankName}" valueMessagePrefix="accounts.bankName"/>

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'bankAddress', 'error')} required">
	<label for="bankAddress">
		<g:message code="accounts.bankAddress.label" default="Bank Address" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="bankAddress" required="" value="${accountsInstance?.bankAddress}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'bankPhone', 'error')} required">
	<label for="bankPhone">
		<g:message code="accounts.bankPhone.label" default="Bank Phone" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="bankPhone" required="" value="${accountsInstance?.bankPhone}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'isActive', 'error')} ">
	<label for="isActive">
		<g:message code="accounts.isActive.label" default="Is Active" />
		
	</label>
	<g:checkBox name="isActive" value="${accountsInstance?.isActive}" />

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'createdAt', 'error')} required">
	<label for="createdAt">
		<g:message code="accounts.createdAt.label" default="Created At" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="createdAt" precision="day"  value="${accountsInstance?.createdAt}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'deletedAt', 'error')} required">
	<label for="deletedAt">
		<g:message code="accounts.deletedAt.label" default="Deleted At" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="deletedAt" precision="day"  value="${accountsInstance?.deletedAt}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: accountsInstance, field: 'updatedAt', 'error')} required">
	<label for="updatedAt">
		<g:message code="accounts.updatedAt.label" default="Updated At" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="updatedAt" precision="day"  value="${accountsInstance?.updatedAt}"  />

</div>

grails-app/views/accounts/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'accounts.label', default: 'Accounts')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-accounts" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-accounts" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${accountsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${accountsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:accountsInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/accounts/detail.gsp
<%--
  Created by IntelliJ IDEA.
  User: Abdur Rahman
  Date: 6/24/2019
  Time: 10:37 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
    <g:set var="entityName" value="${message(code: 'accounts.label', default: 'Accounts')}" />
    <title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
<g:if test="${accountsInstance?.isActive}">
    <li class="fieldcontain">
        <span id="isActive-label" class="property-label"><g:message code="accounts.isActive.label" default="Is Active" /></span>

        <span class="property-value" aria-labelledby="isActive-label"><g:formatBoolean boolean="${accountsInstance?.isActive}" /></span>

    </li>
</g:if>
<g:fieldValue bean="${accountsInstance}" field="name"/>
<g:fieldValue bean="${accontsInstance}" field="bankName"/>
</body>
</html>

grails-app/views/accounts/edit.gsp
<%@ page import="accounting.Accounts" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'accounts.label', default: 'Accounts')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-accounts" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-accounts" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${accountsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${accountsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:accountsInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${accountsInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/accounts/index.gsp
<%@ page import="accounting.Accounts" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'accounts.label', default: 'Accounts')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-accounts" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-accounts" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'accounts.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="number" title="${message(code: 'accounts.number.label', default: 'Number')}" />
					
						<g:sortableColumn property="openingBalance" title="${message(code: 'accounts.openingBalance.label', default: 'Opening Balance')}" />
					
						<g:sortableColumn property="bankName" title="${message(code: 'accounts.bankName.label', default: 'Bank Name')}" />
					
						<g:sortableColumn property="bankAddress" title="${message(code: 'accounts.bankAddress.label', default: 'Bank Address')}" />
					
						<g:sortableColumn property="bankPhone" title="${message(code: 'accounts.bankPhone.label', default: 'Bank Phone')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${accountsInstanceList}" status="i" var="accountsInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${accountsInstance.id}">${fieldValue(bean: accountsInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: accountsInstance, field: "number")}</td>
					
						<td>${fieldValue(bean: accountsInstance, field: "openingBalance")}</td>
					
						<td>${fieldValue(bean: accountsInstance, field: "bankName")}</td>
					
						<td>${fieldValue(bean: accountsInstance, field: "bankAddress")}</td>
					
						<td>${fieldValue(bean: accountsInstance, field: "bankPhone")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
		</div>
	</body>
</html>

grails-app/views/accounts/show.gsp
<%@ page import="accounting.Accounts" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'accounts.label', default: 'Accounts')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-accounts" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-accounts" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list accounts">
			
				<g:if test="${accountsInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="accounts.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${accountsInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.number}">
				<li class="fieldcontain">
					<span id="number-label" class="property-label"><g:message code="accounts.number.label" default="Number" /></span>
					
						<span class="property-value" aria-labelledby="number-label"><g:fieldValue bean="${accountsInstance}" field="number"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.openingBalance}">
				<li class="fieldcontain">
					<span id="openingBalance-label" class="property-label"><g:message code="accounts.openingBalance.label" default="Opening Balance" /></span>
					
						<span class="property-value" aria-labelledby="openingBalance-label"><g:fieldValue bean="${accountsInstance}" field="openingBalance"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.bankName}">
				<li class="fieldcontain">
					<span id="bankName-label" class="property-label"><g:message code="accounts.bankName.label" default="Bank Name" /></span>
					
						<span class="property-value" aria-labelledby="bankName-label"><g:fieldValue bean="${accountsInstance}" field="bankName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.bankAddress}">
				<li class="fieldcontain">
					<span id="bankAddress-label" class="property-label"><g:message code="accounts.bankAddress.label" default="Bank Address" /></span>
					
						<span class="property-value" aria-labelledby="bankAddress-label"><g:fieldValue bean="${accountsInstance}" field="bankAddress"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.bankPhone}">
				<li class="fieldcontain">
					<span id="bankPhone-label" class="property-label"><g:message code="accounts.bankPhone.label" default="Bank Phone" /></span>
					
						<span class="property-value" aria-labelledby="bankPhone-label"><g:fieldValue bean="${accountsInstance}" field="bankPhone"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.isActive}">
				<li class="fieldcontain">
					<span id="isActive-label" class="property-label"><g:message code="accounts.isActive.label" default="Is Active" /></span>
					
						<span class="property-value" aria-labelledby="isActive-label"><g:formatBoolean boolean="${accountsInstance?.isActive}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.createdAt}">
				<li class="fieldcontain">
					<span id="createdAt-label" class="property-label"><g:message code="accounts.createdAt.label" default="Created At" /></span>
					
						<span class="property-value" aria-labelledby="createdAt-label"><g:formatDate date="${accountsInstance?.createdAt}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.deletedAt}">
				<li class="fieldcontain">
					<span id="deletedAt-label" class="property-label"><g:message code="accounts.deletedAt.label" default="Deleted At" /></span>
					
						<span class="property-value" aria-labelledby="deletedAt-label"><g:formatDate date="${accountsInstance?.deletedAt}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${accountsInstance?.updatedAt}">
				<li class="fieldcontain">
					<span id="updatedAt-label" class="property-label"><g:message code="accounts.updatedAt.label" default="Updated At" /></span>
					
						<span class="property-value" aria-labelledby="updatedAt-label"><g:formatDate date="${accountsInstance?.updatedAt}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:accountsInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${accountsInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:stylesheet src="style.css"/>
		<asset:javascript src="application.js"/>
		<asset:stylesheet src="bootstrap.css"/>
		<asset:javascript src="bootstrap.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div class="container-fluid">
			<div class="card card-default">
				<div class="card-body">
					<div class="row">
						<div class="col-md-12">
							<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="softrithm.png" alt="Softrithm"/></a></div>
						</div>
						<div class="col-md-2">
							<nav class="navbar bg-light sidebar">
								<ul class="navbar-nav">
									<li class="nav-item">
										<a class="nav-link" href="#">Dashboard</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="#">Income</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="#">Expense</a>
									</li>
								</ul>
							</nav>
						</div>
						<div class="col-md-10">
							<g:layoutBody/>
						</div>
					</div>
				</div>
				<div class="card-footer pagefooter">
					<span>All Right Reserved by Softrithm IT Ltd</span>
				</div>
			</div>

		</div>

	</body>
</html>